#### Tensors

In [1]:
import torch
import math

##### Creating Tensors

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


##### Random Tensors and Seeding

In [4]:
zeros = torch.zeros(2 ,3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [8]:
print(random1 == random2)
print(random1 == random3)
print(random1 == random4)

tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


##### Tensor Shapes

In [12]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[4.5170e+30, 4.5670e-41, 2.5314e-34],
         [0.0000e+00, 4.4842e-44, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 2.5440e-34],
         [0.0000e+00, 8.9683e-44, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [17]:
some_constants = torch.tensor([[3.141516, 2.71828]])
print(some_constants)
print(some_constants.shape)

some_constants = torch.tensor([[3.141516, 2.71828], [1.6183, 0.0072897]])
print(some_constants)
print(some_constants.shape)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17))
print(some_integers)
print(some_integers.shape)

some_integers = torch.tensor([2, 3, 5, 7, 11, 13, 17])
print(some_integers)
print(some_integers.shape)

tensor([[3.1415, 2.7183]])
torch.Size([1, 2])
tensor([[3.1415, 2.7183],
        [1.6183, 0.0073]])
torch.Size([2, 2])
tensor([ 2,  3,  5,  7, 11, 13, 17])
torch.Size([7])
tensor([ 2,  3,  5,  7, 11, 13, 17])
torch.Size([7])


##### Tensors Datatype

In [22]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

d = b.to(torch.bool)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[12.3902, 15.0541, 16.8179],
        [17.7174, 14.2091, 18.9694]], dtype=torch.float64)
tensor([[12, 15, 16],
        [17, 14, 18]], dtype=torch.int32)
tensor([[True, True, True],
        [True, True, True]])


##### Math & Logic with PyTorch Tensors

In [27]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 -1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)


tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [30]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [32]:
# broadcasting
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)
print(rand)
print(doubled)

tensor([[0.4567, 0.0649, 0.6677, 0.7826],
        [0.1332, 0.0023, 0.4945, 0.3857]])
tensor([[0.9134, 0.1298, 1.3355, 1.5652],
        [0.2663, 0.0045, 0.9890, 0.7715]])


In [33]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2)
print(b)

c = a * torch.rand(3, 1)
print(c)

d = a * torch.rand(1, 2)
print(d)

tensor([[[0.9883, 0.4762],
         [0.7242, 0.0776],
         [0.4004, 0.9877]],

        [[0.9883, 0.4762],
         [0.7242, 0.0776],
         [0.4004, 0.9877]],

        [[0.9883, 0.4762],
         [0.7242, 0.0776],
         [0.4004, 0.9877]],

        [[0.9883, 0.4762],
         [0.7242, 0.0776],
         [0.4004, 0.9877]]])
tensor([[[0.0352, 0.0352],
         [0.0905, 0.0905],
         [0.4485, 0.4485]],

        [[0.0352, 0.0352],
         [0.0905, 0.0905],
         [0.4485, 0.4485]],

        [[0.0352, 0.0352],
         [0.0905, 0.0905],
         [0.4485, 0.4485]],

        [[0.0352, 0.0352],
         [0.0905, 0.0905],
         [0.4485, 0.4485]]])
tensor([[[0.8740, 0.2526],
         [0.8740, 0.2526],
         [0.8740, 0.2526]],

        [[0.8740, 0.2526],
         [0.8740, 0.2526],
         [0.8740, 0.2526]],

        [[0.8740, 0.2526],
         [0.8740, 0.2526],
         [0.8740, 0.2526]],

        [[0.8740, 0.2526],
         [0.8740, 0.2526],
         [0.8740, 0.2526]]])


In [42]:
print(torch.max(a))
print(torch.max(a).item())
print(math.pi)

tensor(1.)
1.0
3.141592653589793


##### Copying Tensors

In [46]:
print(id(a))

139975502611056


In [47]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [49]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a
print(torch.eq(a, b))

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [51]:
a = torch.rand(2, 2, requires_grad=True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

tensor([[0.8441, 0.9004],
        [0.3995, 0.6324]], requires_grad=True)
tensor([[0.8441, 0.9004],
        [0.3995, 0.6324]], grad_fn=<CloneBackward0>)
tensor([[0.8441, 0.9004],
        [0.3995, 0.6324]])


##### Moving to GPU

In [53]:
if torch.cuda.is_available():
    print('We have GPU!')
else:
    print('Sorry, CPU only')

We have GPU!


In [54]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


In [56]:
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

print('Device: {}'.format(device))    
x = torch.rand(2, 2, device=device)

Device: cuda


In [57]:
y = torch.rand(2, 2)
y = y.to(device)

##### Tensor Shapes

In [62]:
a = torch.rand(3, 226, 226)
print(a.shape)
b = a.unsqueeze(0)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [65]:
a = torch.rand(1, 20)
print(a.shape)

# só funciona se o shape começa com 1
b = a.squeeze(0)
print(b.shape)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
torch.Size([20])
torch.Size([2, 2])
torch.Size([2, 2])


In [67]:
# versão inplace
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [70]:
output3d = torch.rand(6, 20 , 20)
print(output3d.shape)

# flatten
input1d = output3d.reshape( 6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


##### Numpy Brigde

In [72]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [73]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.1270, 0.3857, 0.4411],
        [0.2386, 0.5137, 0.8378]])
[[0.1269936  0.3856821  0.44113344]
 [0.23863143 0.5137113  0.8378422 ]]
